public class UsernameException extends Exception{
    private String oldUsername;
    private String username;

    public UsernameException(String username) {
        oldUsername = username;
        this.username = generateUsername();
    }

    public String getNewUsername() {
        return username;
    }

    public String generateUsername() {
        return "USR" + (int) ((Math.random() * ((999999 - 000001) + 1)) + 000001) + "U";
    }

    public String toString() {
        return " The Plan Username " + oldUsername + " was not valid and a new Username (" + username + ") is generated by admin and assigned for the Plan";
    }
}

